import Head from "next/head";
import { enableStaticRendering, observer } from "mobx-react-lite";
import {
  formReset,
  isFormEmpty,
  isFormTouched,
  TextField,
} from "mobx-form-lite";
import { useState } from "react";

enableStaticRendering(typeof window === "undefined");

class FormStore {
  form = {
    name: new TextField(""),
    email: new TextField(""),
  };
}

export const NativeHtmlForm = observer(() => {
  const [store] = useState(() => new FormStore());
  const { form } = store;

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        alert(`Name: ${form.name.value}, Email: ${form.email.value}`);
      }}
    >
      <div>
        <label htmlFor="name">Name</label>
        <input
          id="name"
          name="name"
          type="text"
          value={form.name.value}
          onChange={(e) => form.name.onChange(e.target.value)}
        />
      </div>
      <div>
        <label htmlFor="email">Email</label>
        <input
          id="email"
          name="email"
          type="email"
          value={form.email.value}
          onChange={(e) => form.email.onChange(e.target.value)}
        />
      </div>
      <button type="submit" disabled={isFormEmpty(form)}>
        Submit
      </button>
      <button
        type="button"
        disabled={!isFormTouched(form)}
        onClick={() => {
          formReset(form);
        }}
      >
        Reset
      </button>
    </form>
  );
});

const Home = observer(() => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NativeHtmlForm />
    </>
  );
});

export default Home;
